name: CI  # Название workflow

on:
  push:
    branches: [ main ]  # Запускать workflow при пуше в ветку main
  pull_request:
    branches: [ main ]  # Запускать workflow при создании pull request в ветку main

jobs:
  build:  # Название работы
    runs-on: ubuntu-latest  # Использовать последнюю версию Ubuntu

    steps:  # Шаги, которые будут выполнены
    - name: Checkout repository  # Шаг 1: Клонирование репозитория
      uses: actions/checkout@v2  # Использовать действие actions/checkout версии 2

    - name: Set up Python  # Шаг 2: Установка Python
      uses: actions/setup-python@v2  # Использовать действие actions/setup-python версии 2
      with:
        python-version: '3.x'  # Указать версию Python (замените '3.x' на нужную версию, например '3.8')

    - name: Install dependencies  # Шаг 3: Установка зависимостей
      run: |
        python -m pip install --upgrade pip  # Обновление pip

    - name: Run tests  # Шаг 4: Запуск тестов
      run: |
        pytest  # Команда для запуска тестов (замените на команду, подходящую для вашего проекта)

